ALTER TABLE student_grants
DROP COLUMN april;
ALTER TABLE student_grants
DROP COLUMN august;
ALTER TABLE student_grants
DROP COLUMN get_date;
ALTER TABLE student_grants
DROP COLUMN december;
ALTER TABLE student_grants
DROP COLUMN february;
ALTER TABLE student_grants
DROP COLUMN january;
ALTER TABLE student_grants
DROP COLUMN july;
ALTER TABLE student_grants
DROP COLUMN june;
ALTER TABLE student_grants
DROP COLUMN march;
ALTER TABLE student_grants
DROP COLUMN may;
ALTER TABLE student_grants
DROP COLUMN november;
ALTER TABLE student_grants
DROP COLUMN october;
ALTER TABLE student_grants
DROP COLUMN september;
ALTER TABLE student_grants
DROP COLUMN year;
